export const roadmapOrder = [
  { id: 1, section: "English", levelTitle: "Topic Development", optionName: "English of Writing" },
  { id: 2, section: "English", levelTitle: "Organization and Transitions", optionName: "English of Writing" },
  { id: 3, section: "English", levelTitle: "Full Production of Writing", optionName: "English of Writing" },
  { id: 4, section: "English", levelTitle: "Sentence Structure", optionName: "Conventions of Standard English" },
  { id: 5, section: "English", levelTitle: "Grammar and Usage", optionName: "Conventions of Standard English" },
  { id: 6, section: "English", levelTitle: "Punctuation Conventions", optionName: "Conventions of Standard English" },
  { id: 7, section: "English", levelTitle: "Word Choice", optionName: "Knowledge of Language" },
  { id: 8, section: "English", levelTitle: "Style and Tone", optionName: "Knowledge of Language" },
  { id: 9, section: "English", levelTitle: "Concision and Clarity", optionName: "Knowledge of Language" },
  { id: 10, section: "Mathematics", levelTitle: "Linear Equations", optionName: "Algebra" },
  { id: 11, section: "Mathematics", levelTitle: "Quadratic Equations", optionName: "Algebra" },
  { id: 12, section: "Mathematics", levelTitle: "Polynomials", optionName: "Algebra" },
  { id: 13, section: "Mathematics", levelTitle: "Function Notation", optionName: "Functions" },
  { id: 14, section: "Mathematics", levelTitle: "Linear and Exponential", optionName: "Functions" },
  { id: 15, section: "Mathematics", levelTitle: "Transformations", optionName: "Functions" },
  { id: 16, section: "Mathematics", levelTitle: "Shapes and Angles", optionName: "Geometry" },
  { id: 17, section: "Mathematics", levelTitle: "Circles", optionName: "Geometry" },
  { id: 18, section: "Mathematics", levelTitle: "Coordinate Geometry", optionName: "Geometry" },
  { id: 19, section: "Mathematics", levelTitle: "Real Numbers", optionName: "Number and Quantity" },
  { id: 20, section: "Mathematics", levelTitle: "Ratios and Proportions", optionName: "Number and Quantity" },
  { id: 21, section: "Mathematics", levelTitle: "Complex Numbers", optionName: "Number and Quantity" },
  { id: 22, section: "Mathematics", levelTitle: "Statistical Measures", optionName: "Statistics and Probability" },
  { id: 23, section: "Mathematics", levelTitle: "Probability Models", optionName: "Statistics and Probability" },
  { id: 24, section: "Mathematics", levelTitle: "Sequences and Series", optionName: "Statistics and Probability" },
  { id: 25, section: "Mathematics", levelTitle: "Multi-Step Problems", optionName: "Integrating Essential Skills" },
  { id: 26, section: "Mathematics", levelTitle: "Word Problems", optionName: "Integrating Essential Skills" },
  { id: 27, section: "Mathematics", levelTitle: "Rates and Percentages", optionName: "Integrating Essential Skills" },
  { id: 28, section: "Reading", levelTitle: "Key Ideas and Details 1", optionName: "Key Ideas & Details" },
  { id: 29, section: "Reading", levelTitle: "Key Ideas and Details 2", optionName: "Key Ideas & Details" },
  { id: 30, section: "Reading", levelTitle: "Craft and Structure 1", optionName: "Craft and Structure" },
  { id: 31, section: "Reading", levelTitle: "Craft and Structure 2", optionName: "Craft and Structure" },
  { id: 32, section: "Reading", levelTitle: "Integration 1", optionName: "Integration" },
  { id: 33, section: "Science", levelTitle: "Tables and Graphs 1", optionName: "Interpretation of Data" },
  { id: 34, section: "Science", levelTitle: "Tables and Graphs 2", optionName: "Interpretation of Data" },
  { id: 35, section: "Science", levelTitle: "Interpolate Extrapolate", optionName: "Interpretation of Data" },
  { id: 36, section: "Science", levelTitle: "Scientific Investigation 1", optionName: "Scientific Investigation" },
  { id: 37, section: "Science", levelTitle: "Scientific Investigation 2", optionName: "Scientific Investigation" },
  { id: 38, section: "Science", levelTitle: "Scientific Investigation 3", optionName: "Scientific Investigation" },
  { id: 39, section: "Science", levelTitle: "Data Representation", optionName: "Evaluation of Scientific Arguments" },
  { id: 40, section: "Science", levelTitle: "Research Summaries", optionName: "Evaluation of Scientific Arguments" },
  { id: 41, section: "Science", levelTitle: "Conflicting Viewpoints", optionName: "Evaluation of Scientific Arguments" },
];